#
# Welcome to LYDDE Group Website system
# Version : 1.0.0
#
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Theme
#
remote_theme: lydde/jekyll-lydde-theme

#
# Hosting
#
url: "" # the base hostname & protocol for your site, e.g. https://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /news/:categories/:title # the subpath of your posts, e.g. /news

#
# Plugins
#
plugins:
  - jekyll-relative-links   #https://github.com/benbalter/jekyll-relative-links
  - jekyll-github-metadata  #https://github.com/jekyll/github-metadata
  - jekyll-redirect-from    #https://github.com/jekyll/jekyll-redirect-from
  - jekyll-remote-theme     #https://github.com/benbalter/jekyll-remote-theme

#
# Files excluded
#
exclude:
  - readme.md
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - "*.gemspec"
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
